# Dependencies
highlighter:      pygments

# Setup
title:            Mockup
description:      'A proof of concept for standalone HTML documentation for PSG developers.'
url:              'https://proof-of-concept.gitlab.io'
baseurl:          ''
permalink:        pretty
