# Dependencies
highlighter:      pygments

# Setup
title:            Mockup
description:      'A proof of concept for standalone HTML documentation for PSG developers.'
url:              'https://michelle-hu-2021.github.io'
baseurl:          '/mockup'
permalink:        pretty
